---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: 'example'
  subject:
    organizations:
      - chainguard
  secretName: root-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - '*.ky-rafaels.com'
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-secret
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: chainguard.dev
  namespace: cert-manager
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet
  - useDefaultCAs: true
  - secret:
      name: root-secret
      key: ca.crt
  target:
    configMap:
      key: "bundle.pem"
    # additionalFormats:
    #   jks:
    #     key: "bundle.jks"
    #   pkcs12:
    #     key: "bundle.p12"
    namespaceSelector:
      matchLabels:
        create-certs: "true"