server:
  args:
    oidcIssuer: "http://localhost:8080/realms/sigstore"
    oidcClientID: "sigstore"
    oidcClientSecret: "iHTF2wUHCLtXflgnGXwD4ZI3tAkEIHnM" 
    oidcRedirectURL: "http://fulcio.ky-rafaels.example.com/v1/callback"
    rekorURL: http://rekor.rekor-system.svc.cluster.local
  image:
    registry: cgr.dev
    repository: ky-rafaels.example.com/fulcio
    version: "1.6.6"
createcerts:
  image:
    repository: ky-rafaels.example.com/sigstore-scaffolding-fulcio-createcerts
    version: "0.7.21"