fulcio:
  createcerts:
    enabled: true
  server:
    className: nginx
    ingress:
      http:
        enabled: true
        hosts:
        - host: fulcio.example.com
          path: /
  config:
    format: json
    contents:
      {
        "OIDCIssuers": {
          "http://keycloak.example.com/realms/sigstore": {
            "IssuerURL": "http://keycloak.example.com/realms/sigstore",
            "ClientID": "sigstore",
            "Type": "email",
            "IssuerClaim": "iss"
          }
        },
        "CTLogURL": "http://rekor.example.com"
      }
rekor:
  server:
    # image:
    #   registry: cgr.dev
    #   repository: ky-rafaels.example.com/rekor-server
    #   version: 1.3.9
    attestation_storage:
      enabled: false
      persistence:
        enabled: false
    ingress:
      enabled: true
      hostname: "rekor.example.com"
      className: nginx
      hosts:
      - path: /
        host: rekor.example.com
tuf:
  enabled: true
  ingress:
    className: nginx
    http:
      hosts:
      - path: /
        host: "tuf.example.com"
  secrets:
    tsa:
      enabled: false
copySecretJob:
  enabled: true
tsa:
  enabled: false