server:
  args:
    oidcIssuer: "https://keycloak.example.com/auth/realms/sigstore"
    oidcClientID: "fulcio-client"
    # oidcClientSecret: "<client-secret-from-keycloak>"
    oidcRedirectURL: "http://fulcio.example.com/v1/callback"
    rekorURL: http://rekor.rekor-system.svc.cluster.local
  image:
    registry: cgr.dev
    repository: ky-rafaels.example.com/fulcio
    version: "1.6.6"
createcerts:
  image:
    repository: ky-rafaels.example.com/sigstore-scaffolding-fulcio-createcerts
    version: "0.7.21"